### ISSUE TITLE
Come up with a better name

### ISSUE THREAD

**Issue by jgallen23** [jgallen23/mongroup#1]
http://thesaurus.com/browse/monitor?s=t
http://thesaurus.com/browse/sentinel?s=ts

**Comment by ovaillancourt** [comment]
[mon-mothma](http://starwars.wikia.com/wiki/Mon_Mothma) - cause mon processes need a leader :P

(Good job with the module btw, very useful w/ mon, we're using it in production here and it works like a charm.)

**Comment by thomsbg** [comment]
Fwiw, I like the mon / mongroup combo.  Self explanatory and unix-y.

**Comment by flexd** [comment]
I like mon and mongroup.

**Comment by jgallen23** [comment]
closing.  just going to stick with mongroup
