### ISSUE TITLE
when specifying the config file location, the default `status` command doesn't work

### ISSUE THREAD

**Issue by weisjohn** [jgallen23/mongroup#16]
First command works, second doesn't.

```
$ ./bin/mongroup -c example/mongroup.conf status

         web : dead
        web2 : dead
        web3 : dead
        web4 : dead
        web5 : dead

$ ./bin/mongroup -c example/mongroup.conf
$
```

This may seem like a trivial issue but I wanted to just alias `mg` to `mg -c ~/conf/mongroup.con`, therefore being able to `mg` to get the status and still use `mg stop` or `mg start`, etc. etc.

**Comment by weisjohn** [comment]
Thanks @jgallen23!

**Comment by otsaw** [comment]
This fix doesn't make sense, e.g. `mongroup start foo` is two arguments and gets caught in that `if` and tries to set `foo` as a config file.

I'm no shell script expert -- does that argument parsing `while` loop shift all arguments? Can't you check `$2` being blank under `-c` of the `while` loop and if so then call `status`?
